name: Deploy

on:
  - release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy on pypi
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        echo -e "[pypi]" >> ~/.pypirc
        echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
        echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
        pip install twine wheel
        make deploy
